[package]
name = "net_cerbonix_ssotickets"
description = "Issues single-use login tickets so ClientXCMS can sign a customer into the panel."
authors = ["Cerbonix"]
version = "0.1.0"
edition = { workspace = true }

[dependencies]
shared = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
compact_str = { workspace = true }
indexmap = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tower-cookies = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
uuid = { workspace = true }
